package com.example.partner.platform;

public enum LoggingEvent {

    CREATE_USER, 
    ADD_PROFESSIONAL_PROFILE, 
    ADD_PERSONAL_PROFILE,
    UPDATE_PERSONAL_PROFILE,
    CONFIRM_PACK,
    RETRIEVE_USER_PROFILE,
    AUTHENTICATE_USER_WITH_CREDENTIAL, 
    AUTHENTICATE_WITH_PROVIDER, 
    VERIFY_AUTHENTICATION_TOKEN,

    ADD_AGENCY,
    UPDATE_AGENCY,
    RETRIEVE_AGENCIES,
    ADD_BRANCH,
    RETRIEVE_BRANCHES,
    UPDATE_BRANCH,
    RETRIEVE_REGIONS_BY_AGENCY_ID,
    ADD_REGION,
    RETRIEVE_REGIONS,
    RETRIEVE_REGION_BY_ID,
    UPDATE_REGION,
    ADD_PRODUCER,
    UPDATE_PRODUCER,
    RETRIEVE_PRODUCER,
    RETRIEVE_PRODUCERS,
    ADD_LEAD_URL,
    RETRIEVE_LEAD_URL,
    RETRIEVE_LEAD_URLS,
    UPLOAD_PROSPECT_LIST;

}
